### ISSUE TITLE
Slette fra startliste feiler

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#115]
Kan være relatert til valideringsfeil.

event-service-gui_1           | ERROR:root:delete_start_entry failed - 500 - {'detail': 'Races in raceplan not sorted on start-time.'}
event-service-gui_1           | ERROR:root:Error: Error - 500: Races in raceplan not sorted on start-time..
event-service-gui_1           | 213.239.110.138 [04/Jan/2023:18:53:30 +0000] "POST /start_edit HTTP/1.1" 303 376 "http://sprint-demo2.northeurope.cloudapp.azure.com:8080/start_edit?event_id=7eeefaec-960b-4678-8cc6-99e37972979f&klasse=M17&action=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"

event-service-gui_1           | 213.239.110.138 [04/Jan/2023:18:53:27 +0000] "GET /start_edit?event_id=7eeefaec-960b-4678-8cc6-99e37972979f&klasse=M17&action= HTTP/1.1" 200 18529 "http://sprint-demo2.northeurope.cloudapp.azure.com:8080/start_edit?event_id=7eeefaec-960b-4678-8cc6-99e37972979f" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"
event-service_1               | {"message": "172.19.0.7 [04/Jan/2023:18:53:30 +0000] \"GET /events/7eeefaec-960b-4678-8cc6-99e37972979f HTTP/1.1\" 200 422 \"-\" \"Python/3.10 aiohttp/3.8.3\"", "remote_address": "172.19.0.7", "request_start_time": "[04/Jan/2023:18:53:30 +0000]", "first_request_line": "GET /events/7eeefaec-960b-4678-8cc6-99e37972979f HTTP/1.1", "response_status": 200, "response_size": 422, "request_header": {"Referer": "-", "User-Agent": "Python/3.10 aiohttp/3.8.3"}, "severity": "INFO", "serviceContext": {"service": "event-service"}}
user-service_1                | 172.19.0.8 [04/Jan/2023:18:53:30 +0000] "POST /authorize HTTP/1.1" 204 99 "-" "Python/3.10 aiohttp/3.8.3"
event-service_1               | {"message": "EventFormat with for event id 7eeefaec-960b-4678-8cc6-99e37972979f not found", "exc_info": "Traceback (most recent call last):\n  File \"/app/event_service/views/event_format.py\", line 89, in get\n    event_format = await EventFormatService.get_event_format(db, event_id)\n  File \"/app/event_service/services/event_format_service.py\", line 80, in get_event_format\n    raise EventFormatNotFoundException(\nevent_service.services.event_format_service.EventFormatNotFoundException: EventFormat with for event id 7eeefaec-960b-4678-8cc6-99e37972979f not found\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp_middlewares/error.py\", line 210, in middleware\n    return await handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py\", line 954, in _iter\n    resp = await method()\n  File \"/app/event_service/views/event_format.py\", line 91, in get\n    raise HTTPNotFound(reason=str(e)) from e\naiohttp.web_exceptions.HTTPNotFound: EventFormat with for event id 7eeefaec-960b-4678-8cc6-99e37972979f not found", "severity": "ERROR", "serviceContext": {"service": "event-service"}}
event-service_1               | {"message": "172.19.0.8 [04/Jan/2023:18:53:30 +0000] \"GET /events/7eeefaec-960b-4678-8cc6-99e37972979f/format HTTP/1.1\" 404 255 \"-\" \"Python/3.10 aiohttp/3.8.3\"", "remote_address": "172.19.0.8", "request_start_time": "[04/Jan/2023:18:53:30 +0000]", "first_request_line": "GET /events/7eeefaec-960b-4678-8cc6-99e37972979f/format HTTP/1.1", "response_status": 404, "response_size": 255, "request_header": {"Referer": "-", "User-Agent": "Python/3.10 aiohttp/3.8.3"}, "severity": "INFO", "serviceContext": {"service": "event-service"}}
event-service_1               | {"message": "172.19.0.8 [04/Jan/2023:18:53:30 +0000] \"GET /events/7eeefaec-960b-4678-8cc6-99e37972979f HTTP/1.1\" 200 422 \"-\" \"Python/3.10 aiohttp/3.8.3\"", "remote_address": "172.19.0.8", "request_start_time": "[04/Jan/2023:18:53:30 +0000]", "first_request_line": "GET /events/7eeefaec-960b-4678-8cc6-99e37972979f HTTP/1.1", "response_status": 200, "response_size": 422, "request_header": {"Referer": "-", "User-Agent": "Python/3.10 aiohttp/3.8.3"}, "severity": "INFO", "serviceContext": {"service": "event-service"}}
competition-format-service_1  | {"message": "172.19.0.8 [04/Jan/2023:18:53:30 +0000] \"GET /competition-formats?name=Individual+Sprint HTTP/1.1\" 200 4520 \"-\" \"Python/3.10 aiohttp/3.8.3\"", "remote_address": "172.19.0.8", "request_start_time": "[04/Jan/2023:18:53:30 +0000]", "first_request_line": "GET /competition-formats?name=Individual+Sprint HTTP/1.1", "response_status": 200, "response_size": 4520, "request_header": {"Referer": "-", "User-Agent": "Python/3.10 aiohttp/3.8.3"}, "severity": "INFO", "serviceContext": {"service": "competition-format-service"}}
race-service_1                | {"message": "Races in raceplan not sorted on start-time.", "exc_info": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp_middlewares/error.py\", line 210, in middleware\n    return await handler(request)\n  File \"/usr/local/lib/python3.10/site-packages/aiohttp/web_urldispatcher.py\", line 954, in _iter\n    resp = await method()\n  File \"/app/race_service/views/start_entries.py\", line 302, in delete\n    await RaceplansService.update_raceplan(db, raceplan.id, raceplan)  # type: ignore\n  File \"/app/race_service/services/raceplans_service.py\", line 125, in update_raceplan\n    await validate_raceplan(db, raceplan)\n  File \"/app/race_service/services/raceplans_service.py\", line 161, in validate_raceplan\n    raise IllegalValueException(\"Races in raceplan not sorted on start-time.\")\nrace_service.services.exceptions.IllegalValueException: Races in raceplan not sorted on start-time.", "severity": "ERROR", "serviceContext": {"service": "race-service"}}
race-service_1                | {"message": "172.19.0.7 [04/Jan/2023:18:53:30 +0000] \"DELETE /races/3a76430b-b5fa-49dc-8241-8ad8c49e0b29/start-entries/a437cbff-e6bb-4218-95d6-7f0574f6b099 HTTP/1.1\" 500 234 \"-\" \"Python/3.10 aiohttp/3.8.3\"", "remote_address": "172.19.0.7", "request_start_time": "[04/Jan/2023:18:53:30 +0000]", "first_request_line": "DELETE /races/3a76430b-b5fa-49dc-8241-8ad8c49e0b29/start-entries/a437cbff-e6bb-4218-95d6-7f0574f6b099 HTTP/1.1", "response_status": 500, "response_size": 234, "request_header": {"Referer": "-", "User-Agent": "Python/3.10 aiohttp/3.8.3"}, "severity": "INFO", "serviceContext": {"service": "race-service"}}
event-service-gui_1           | ERROR:root:delete_start_entry failed - 500 - {'detail': 'Races in raceplan not sorted on start-time.'}
event-service-gui_1           | ERROR:root:Error: Error - 500: Races in raceplan not sorted on start-time..
event-service-gui_1           | 213.239.110.138 [04/Jan/2023:18:53:30 +0000] "POST /start_edit HTTP/1.1" 303 376 "http://sprint-demo2.northeurope.cloudapp.azure.com:8080/start_edit?event_id=7eeefaec-960b-4678-8cc6-99e37972979f&klasse=M17&action=" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:108.0) Gecko/20100101 Firefox/108.0"

**Comment by stigbd** [comment]
Root cause til feilen er at races ikkje er i kronologisk orden, sjå https://github.com/langrenn-sprint/race-service/issues/136

Men det blir feil at vi køyrer denne valideringa ved sletting av deltaker. Fjerner validering på kronologisk orden ved opprettelse og update av raceplan. Denne valideringa blir uansett køyrt i egen, dedikert funksjon.

**Comment by stigbd** [comment]
Har gjort ein fiks i race-service som antageligvis løyser dette. Kan du teste, @heming-h ?
