### ISSUE TITLE
Ny metode get_contestants_by_name

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#116]
Lage en søkefunksjon på deltakers navn. Funksjonen bør søke på både fornavn og etternavn og heller gi for mange enn for få treff. 

For eksempel - hvis man søker på navnet "Bjørn" bør svare inneholde alle deltakere som har Bjørn i for- eller etternavn (eller begge).

/events/{eventId}/contestants:
    parameters:
      - name: name
        in: query
        description: first and/or last name
        schema:
          type: string
        example: "Bjørn"

See also: https://github.com/langrenn-sprint/result-service-gui/issues/136

**Comment by stigbd** [comment]
Bra funksjon. Eg foreslår imidlertid å implementere denne som eit søk:

POST /events/{eventId}/contestants/search
der body inneheld valgfrie søkeparametre, feks:
- name
- club

Og søket defaulter til OR mellom søkeparametre.

Desse kan vi utvide etter kvart.
