### ISSUE TITLE
Nytt filformat - validering på alderklasse feiler

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#139]
ERROR:root:create_contestant failed - 422 - {'detail': "Ageclass Gutter 16 is not valid. Must be of the form 'J 12 år', 'J 12/13 år', 'Kvinner junior', 'Felles' or 'Para'."}

Eksempler på klassenavn som benyttes:
Gutter 12
Gutter 10
Jenter 16
Gutter 11
Jenter 9
Gutter 12
Gutter 9

**Comment by stigbd** [comment]
Denne vil bli løst av #140

**Comment by stigbd** [comment]
Enig i det. Men #140 er tenkt som ein feature som legger til støtte for iSonen. Dette inkluderer å endre regexp, samt ein del andre ting.
