### ISSUE TITLE
Tildel startnummer feiler dersom man slår saman klasser og endrer verdi for "Aldersklasser" i ny klasse

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service#149]
Vi lasta opp alle deltakere. Genererte klasser. Fjerna så 5 deltakere. Generert kjøreplan. Gikk så til tildel startnummer. Dette feila med følgande error i backend:
`{"message": "coroutine raised StopIteration", "exc_info": "Traceback (most recent call last):\n  File \"/app/event_service/commands/contestants_commands.py\", line 97, in assign_bibs\n    c_dict[\"raceclass_group\"] = next(\n                                ^^^^^\nStopIteration\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp_middlewares/error.py\", line 211, in middleware\n    return await handler(request)\n           ^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/aiohttp/web_urldispatcher.py\", line 955, in _iter\n    ret = await method()\n          ^^^^^^^^^^^^^^\n  File \"/app/event_service/views/contestants_commands.py\", line 48, in post\n    await ContestantsCommands.assign_bibs(db, event_id)\nRuntimeError: coroutine raised StopIteration", "severity": "ERROR", "serviceContext": {"service": "event-service"}}`

**Comment by heming-langrenn** [comment]
Denne klarer jeg ikke å tolke. Klarer vi å gjenskape den?

**Comment by stigbd** [comment]
Eg gjer eit forsøk lokalt i morgon på å gjenskape. Så skal eg skrive ein test som genererer feilen.

**Comment by stigbd** [comment]
OK, då har eg forstått scenariet:
- Det har ingenting med sletta contenstants å gjere.
1. For å gjenskape må ein slå saman klasser, og endre `aldersklasser` til noko anna enn aldersklasse-verdi på contestants, eks slå saman `Menn 19-20` og `Menn Senior` til løpsklasse `M19-20-S` og gi denne ny ageclasses-verdi til feks "Menn 19-20-S". (Det korrekte er å beholde det som systemet foreslår:  `"Menn senior", "Menn 19-20"`
2. StopIteration skjer når ein forsøker å finne verdi for `group`  og `order`ved å slå opp i raceclasses på `contestant.ageclass`. Denne fins ikkje lenger, pga endringa utført i (1).

Forslag til tiltak:
- Fange StopIteration-feilen og gi fornuftig feilmelding, feks "ageclass for contestant Jon Doe: 'Menn 18-19' does not exist."
- Då vil brukar kunne rette opp i dette ved å endre verdien 
- Vurdere å hindre redigering av feltet `Aldersklasser` ved "Endre klasse".
