### ISSUE TITLE
Forslag til regelsett for fordeling av løpere til heat, A- og C- semifinaler og  A-, B- og C- finaler:

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service#49]
Forslag til regelsett for fordeling av løpere til heat, A- og C- semifinaler og  A-, B- og C- finaler:
| Max no of contestants	|no of heats Q|	To S pr heat |	no of SA | to F pr heat	| no of SC | to FC pr heat | no of F (A-C) |
| --------------------- | ------------|	---- |	-------- | ---	| ---------| ---- | ---- |
| 7  | 0 | All to SA | 1 | All to FA    | 0 |  n/a | 1 |
| 16 | 0 | All to SA | 2 | 4 FA, rest to FB | 0 | n/a  | 2 |
| 24 | 3 | 5 to SA, rest to FC | 2 | 4 FA, rest to FB | 0 | n/a |	3 |
| 32 | 4 | 4 to SA, rest to SC |	2 | 4 FA, rest to FB | 2 |	4 FC, rest out | 3 |
| 40 | 5 | 5 to SA, rest to SC |	3 |	3 FA, 3 FB, rest out |	2	|4 FC, rest out	| 3 |
| 48 | 6 | 4 to SA, rest to SC	| 3	| 3 FA, 3 FB, rest out |	3	|3 FC, rest out	| 3 |
| 56 | 7 | 5 to SA, rest to SC	| 4	| 2 FA, 2 FB, rest out |	3	|3 FC, rest out	| 3 |
| 80 | 8 | 4 to SA, rest to SC	| 4	| 2 FA, 2 FB, rest out |	4	|2 FC, rest out	| 3 |

_Originally posted by @heming-langrenn in https://github.com/langrenn-sprint/issue-tracker/issues/6#issuecomment-921693274_

**Comment by stigbd** [comment]
Dette skal inn i nytt competition-format "Individual sprint competition without a qualification round".

**Comment by heming-langrenn** [comment]
Det skal nok stå 2 FC og ikke 4FC på den siste linja - men ellers ser alt riktig ut.

**Comment by stigbd** [comment]
Angrepsmåte:
1. Først lage plan, dvs at man kan se bort i fra "videre til" kolonnen
2. Så lage startliste 
3. Så fordele løpere til Semi og Finaler basert på resultat i foregående runde. Ta hensyn til "videre til" kolonnen.

**Comment by stigbd** [comment]
Legg til "max_starting_positions" pr heat som konfig-verdi.
Premiss: Det er alltid tre "runder: Kvartfinaler, Semifinaler og Finaler.
Premiss: Det kan vere ulike semifinaler og finaler: Semi A og Semi B, Finale A og Finale B.

**Comment by stigbd** [comment]
Test-triks: Bruk startnummer som plassering i heat i test.

**Comment by heming-langrenn** [comment]
Konfigurerbar matrise som nytt issue.

**Comment by heming-langrenn** [comment]
Hei - @stigbd . Ref spørsmål på slack - det skal aldri flere til FB enn FA - jeg har oppdatert dette, endret fra "rest til FB" til "4 FB, rest out"

**Comment by stigbd** [comment]
> Hei - @stigbd . Ref spørsmål på slack - det skal aldri flere til FB enn FA - jeg har oppdatert dette, endret fra "rest til FB" til "4 FB, rest out"

Ok, fint. Eg sletta forøvrig spørsmålet, for det stemte ikkje, det eg sa der.
