### ISSUE TITLE
Lag mulighet for å slå flere aldersklasser sammen til en rennklasse

### ISSUE THREAD

**Issue by stigbd** [langrenn-sprint/event-service#67]

**Comment by heming-langrenn** [comment]
Hei @stigbd . Vi må gjøre en endring på datamodellen for å kunne støtte flere ageclasses i en raceclass. Jeg ser to muligheter:

1. I Raceclass-klassen, gjøre om "ageclass" til List object slik at vi kan ha flere ageclasses på en raceclass.
2. Snu på det og gjøre om til en Ageclass-klasse og tillate at flere aldersklasser har samme raceclass. Hva tenker du?

Data modellen slik den er i dag:
@dataclass
class Raceclass(DataClassJsonMixin):
    """Data class with details about an raceclass."""

    name: str
    ageclass_name: str
    event_id: str
    no_of_contestants: int = 0
    distance: Optional[str] = field(default=None)
    group: Optional[int] = field(default=None)
    order: Optional[int] = field(default=None)
    id: Optional[str] = field(default=None)

**Comment by stigbd** [comment]
Eg har sett for meg (1). (1) er relativt enkel å implmenetere og gjer omfanget av refaktorering til eit minimum.
