### ISSUE TITLE
Add support for ageclass filter on GET /contestants

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#71]
get_contestants_by_raceclass
get_contestants_by_ageclass

**Comment by stigbd** [comment]
get_contestants_by_raceclass er det støtte for i dag, ref https://github.com/langrenn-sprint/event-service/blob/6b2432bd77d247436d52da63bb2cd6fd4cd19fac/specification.yaml#L245-L250

Men det står igjen å implementere støtte for filter på ageclass.
