### ISSUE TITLE
Test KM SKAGEN - last inn deltakerfil

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#75]
Opprettet deltakere: {'total': 670, 'created': 668, 'updated': 2, 'failures': 0}
Det ser ut til at de to som er "Updated" er i klasse J10 - men jeg klarer ikke å se hvem. Er det mulig å få ut en id på disse i resultatsettet?

Bør legge inn i brukermanual hvordan dette håndteres i excel.

**Comment by stigbd** [comment]
Dessverre så rapporterer ikkje back-end i dag ut id på dei som er oppdatert. Det krever ei litt større endring i responsen. Foreslår vi oppretter issue på dette.

Workaround i dag:
Dersom ein køyrer med logging-level DEBUG, vil du imidlertid finne det i loggen:
```
logging.debug(
                    f"updated event_id/contestant_id: {event_id}/{contestant_id}"
                )
```
Eg gjorde ein rask sjekk i input-fil (reknearket) og har sendt deg dei duplikate utøvarane i e-post.
