### ISSUE TITLE
- Ved generer klasser, tryner med 500 når det ligger syntaktisk feil i feks klasse

### ISSUE THREAD

**Issue by heming-langrenn** [langrenn-sprint/event-service#96]
Ref. feil som genereres av Testfil: -1314.csv - I csv fil er Ida Emilie linja feil. Oppdages ikke i import. Løsning: https://github.com/langrenn-sprint/event-service/issues/69

**Comment by stigbd** [comment]
Følgande regex burde fungere på validering av Klasse:
[JGMK]\s\d*\/?\d+?\sår

Ref https://regex101.com/

**Comment by stigbd** [comment]
Denne sjekken  bør vi også legge inn raceclass-logikken der bruker kan opprette nye klasser
